// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    AddTransaction: typeof import('./src/components/AddTransaction.vue')['default']
    Calendar: typeof import('./src/components/Calendar.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCalendar: typeof import('element-plus/es')['ElCalendar']
    ElCard: typeof import('element-plus/es')['ElCard']
    ElCol: typeof import('element-plus/es')['ElCol']
    ElContainer: typeof import('element-plus/es')['ElContainer']
    ElDivider: typeof import('element-plus/es')['ElDivider']
    ElEmpty: typeof import('element-plus/es')['ElEmpty']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElHeader: typeof import('element-plus/es')['ElHeader']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElInputNumber: typeof import('element-plus/es')['ElInputNumber']
    ElMain: typeof import('element-plus/es')['ElMain']
    ElMenu: typeof import('element-plus/es')['ElMenu']
    ElMenuItem: typeof import('element-plus/es')['ElMenuItem']
    ElMenuItemGroup: typeof import('element-plus/es')['ElMenuItemGroup']
    ElRow: typeof import('element-plus/es')['ElRow']
    ElSpace: typeof import('element-plus/es')['ElSpace']
    ElSubMenu: typeof import('element-plus/es')['ElSubMenu']
    History: typeof import('./src/components/History.vue')['default']
    Menu: typeof import('./src/components/Menu.vue')['default']
    MenuBar: typeof import('./src/components/MenuBar.vue')['default']
    Navbar: typeof import('./src/components/Navbar.vue')['default']
    Tracker: typeof import('./src/components/Tracker.vue')['default']
    TransactionCard: typeof import('./src/components/TransactionCard.vue')['default']
    TransactionForm: typeof import('./src/components/TransactionForm.vue')['default']
    YourBalance: typeof import('./src/components/YourBalance.vue')['default']
  }
}

export { }
